import "./globals.css";
import type { Metadata } from "next";
import LocaleFont from "next/font/local";
import Navbar from "./_components/navbar";
import { ThemeProvider } from "@/provider/theme-provider";

const inter = LocaleFont({
  src: "../public/fonts/inter.ttf",
  variable: "--font-inter",
});
const nunito = LocaleFont({
  src: "../public/fonts/nunito.ttf",
  variable: "--font-nunito",
});
const openSans = LocaleFont({
  src: "../public/fonts/opensans.ttf",
  variable: "--font-opensans",
});

export const metadata: Metadata = {
  title: "Pro Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${nunito.variable} ${openSans.variable} font-inter`}
    >
      <body className="h-full dark:bg-gray-900">
        <ThemeProvider>
          <nav className="fixed left-0 top-0 z-10 h-20 w-full overflow-hidden border-b dark:border-neutral-700">
            <Navbar />
          </nav>

          <main className="h-full pt-20">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
